---
version: '3'
services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8080:3000"
   # depends_on:
   #   - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: incidentesViales
      MYSQL_USER: crudIncidentes
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - "../data:/var/lib/mysql"